name: Deploy Marketing Webpage

on:
  push:
    branches: ["main"]
    paths: ["webpage/**"]
  workflow_dispatch:
permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  deploy:
    uses: leo-lem/leo-lem/.github/workflows/deploy-pages.yml@main
    with:
      path: webpage
