name: Deploy static content to Pages
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["webpage/**"]
jobs:
  deploy:
    uses: leo-lem/leo-lem/.github/workflows/deploy-pages.yml@main
    with:
      path: webpage